- Sources/StringExtractor/ExtractionError.swift
- Sources/StringExtractor/Resource+Extract.swift
- Sources/StringExtractor/Resource+StringUnit.swift
- Sources/StringExtractor/StringExtractor+StringCatalog.swift
- Sources/StringExtractor/StringExtractor+Util.swift
- Sources/StringExtractor/StringExtractor.swift
- Sources/StringExtractor/StringParser.swift
- Sources/StringResource/Resource.swift
- Tests/XCStringsToolTests/GenerateTests.swift
- Tests/XCStringsToolTests/__Fixtures__/!MismatchingArgumentType.xcstrings
- Tests/XCStringsToolTests/__Fixtures__/!MissingArgument.xcstrings
- Tests/XCStringsToolTests/__Fixtures__/Localizable.xcstrings
- Tests/XCStringsToolTests/__Fixtures__/Positional.xcstrings
- Tests/XCStringsToolTests/__Fixtures__/Substitution.xcstrings
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Positional.swift
When using positional specifiers (i.e `%1$@`) to explicitly reposition values or to repeat them, XCStrings Tool would fail to correctly handle this and result in either generating code that required two arguments, or placing the arguments in the wrong positon.
This Pull Request fixes that, and adds some validation that raises issues early on if you have gotten your strings into an invalid state:
1. `"%1$lld or %1$@"`
- A scenario where `arg1` is defined as both `Int` and `String`
3. `"%2$@, %3$@"`
- A scenario where an argument (`arg1`) is omitted from the string
> Fix generation for strings with repeating or reordered arguments 

- Sources/StringExtractor/PlaceholderType.swift
- Tests/XCStringsToolTests/__Fixtures__/FormatSpecifiers.xcstrings
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.FormatSpecifiers.swift
> Add cases for `%u`, `%x` and `%o` to produce `UInt` arguments

- Sources/xcstrings-tool/Generate.swift
fixes #35 
In XcodeCloud environment, file system seems more strict than local machine.
`xcstrings-tool` implementation uses `try someString.write(to: outputURL, atomically: true, encoding: .utf8)` to write generated contents to file. 
When `atomically` is `true` , contents will be written to intermediate file and then file will be moved to `outputURL` . But XcodeCloud seems to deny file writes outside of `pluginWorkDirectory` even if it is temporary file made by Foundation framework.
The easiest way to prevent this error is making `atomically` to be `false` if atomicity is not very important.
What do you think of it?
> Disable use of auxiliary file to prevent permission error on XcodeCloud

- Package.resolved
- Sources/xcstrings-tool/Generate.swift
The latest version of swift-argument-parser has a _fix_ that causes an incompatibility with the current `Generate` command definition:
> - `@Option`- and `@Argument`-annotated optional properties that use a transform closure for parsing can now be declared without ambiguity. (https://github.com/apple/swift-argument-parser/pull/619)
https://github.com/apple/swift-argument-parser/releases/tag/1.3.1
This causes the issue observed in #44.
The fix however is simple, we just need to explicitly annotate `input` and `output` as `URL` so that they are not interpreted as optional types when using 1.3.1.
> Fix compatibility with swift-argument-parser 1.3.1

- Sources/StringGenerator/StringGenerator.swift
- Sources/StringGenerator/SwiftSyntax/AttributeSyntax+Availability.swift
- Sources/StringGenerator/SwiftSyntax/ExtensionDeclSyntax.swift
- Sources/StringGenerator/SwiftSyntax/FunctionCallExprSyntax.swift
- Sources/StringGenerator/SwiftSyntax/FunctionSignatureSyntax.swift
- Sources/StringGenerator/SwiftSyntax/MemberBlockSyntax.swift
- Sources/StringGenerator/SwiftSyntax/SourceFileSyntax.swift
- Sources/StringGenerator/SwiftSyntax/StructDeclSyntax.swift
- Sources/StringGenerator/SwiftSyntax/SyntaxProtocol.swift
- Sources/StringGenerator/SwiftSyntax/TokenSyntax+Import.swift
- Sources/StringGenerator/SwiftSyntax/TokenSyntax+Types.swift
- Tests/PluginTests/PluginTests.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.FormatSpecifiers.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Localizable.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Multiline.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Positional.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Simple.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Substitution.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Variations.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerateWithPackageAccessLevel.Localizable.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerateWithPublicAccessLevel.Localizable.swift
- Closes: #30 
Bit of a WIP, but the initial draft that will allow use of xcstrings-tool on iOS 15/macOS 12.
I still need to add documentation back to the generated code, but its mostly there so can be tested out if you need it urgently.
For a strings table called `Localizable` with a key called `foo`, you can use as follows:
```swift
String(localizable: .foo) // iOS 15+ via String.init(localized:defaultValue:table:locale:bundle:)
String(localized: .localizable.foo) // iOS 16+ via LocalizedStringResource
```
> Support iOS 15/macOS 12

- Sources/StringGenerator/StringGenerator.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.FormatSpecifiers.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Localizable.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Multiline.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Positional.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Simple.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Substitution.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Variations.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerateWithPackageAccessLevel.Localizable.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerateWithPublicAccessLevel.Localizable.swift
Unlike `LocalizedStringResource`, the properties within the generated `String.Localizable` type remain private to the generated source and cannot be directly accessed.
This causes an issue if you need to be able to change the `Locale` value to something other than `.current`.
To address this, I've updated `String.init(localizable:)` to be `String.init(localizable:locale:)`, with a nullable value.
If the custom `locale` is `nil` (the default value), we will use the original locale that is supplied by code generation.
If a value is set, it will take priority and allows you to override the language returned, for example:
```swift
String(localizable: .greeting) // Hello
String(localizable: .greeting, locale: Locale(identifier: "fr")) // Bonjour
```
> Support custom `Locale` when using iOS 15 compatible `String` initialiser

- Package.resolved
- Package.swift
Closes #59 
There were no source incompatibilities, but I didn't have the version requirements setup quite right in Package.swift. This change now allows the use of swift-syntax 509.0.0 through to 511.0.0.
> Bump swift-syntax to 510.0.1

- Sources/StringExtractor/ExtractionError.swift
- Sources/StringExtractor/PlaceholderType.swift
- Sources/StringExtractor/Resource+Extract.swift
- Sources/StringExtractor/StringParser.swift
- Tests/XCStringsToolTests/GenerateTests.swift
- Tests/XCStringsToolTests/__Fixtures__/!UnsupportedFormatSpecifiers.xcstrings
- Tests/XCStringsToolTests/__Fixtures__/FormatSpecifiers.xcstrings
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.FormatSpecifiers.swift
Closes #55 
Parsing these types of format specifiers was added to match the behaviour of other tools, but these types are not supported when using `String.LocalizationValue`. Instead, you must format the string and pass it into your localisation as a `%@` argument. 
This change continues to parse these placeholder types instead of skipping them, but will raise a diagnostic error if they are detected.
> Remove support for `CChar`, `UnsafePointer<CChar>` and `UnsafeRawPointer`

- Sources/Documentation/XCStringsToolPlugin.docc/Integrating XCStrings Tool into an Xcode Project Target.md
- Sources/StringExtractor/Resource+Extract.swift
- Sources/StringGenerator/StringGenerator.swift
- Sources/StringGenerator/SwiftSyntax/ArrayExprSyntax.swift
- Sources/StringGenerator/SwiftSyntax/ExtensionDeclSyntax.swift
- Sources/StringGenerator/SwiftSyntax/TokenSyntax+Types.swift
- Sources/StringResource/Argument.swift
- Tests/XCStringsToolTests/GenerateTests.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.FormatSpecifiers.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Localizable.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Multiline.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Positional.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Simple.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Substitution.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Variations.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerateWithPackageAccessLevel.Localizable.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerateWithPublicAccessLevel.Localizable.swift
Closes #64 
Starting in 0.2.0, the generated source defines `String.LocalizationValue` literals that act as the `defaultValue` when creating instances of `LocalizedStringResource`.
Previously, these values didn't seem to be picked up by Xcode, but with the changes in #50, Xcode seems to pick these up and will put them into your Strings Catalog as a new phrase, which is not what we want.
The `defaultValue` is required as this is the only way to pass the values for each argument into `LocalizedStringResource`, so we can't omit it, but there are alternative ways to generate the source code that prevent it from being detected by Xcode's string extraction...
Since the only way to initialise `String.LocalizationValue` with arguments is to use string interpolation (sugar for …
> Prevent Xcode from extracting generated constants as new localizations

- Sources/StringExtractor/Resource+Extract.swift
- Sources/StringExtractor/Resource+StringUnit.swift
- Sources/StringGenerator/StringGenerator.swift
- Sources/StringResource/Resource.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.FormatSpecifiers.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Localizable.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Multiline.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Positional.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Simple.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Substitution.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Variations.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerateWithPackageAccessLevel.Localizable.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerateWithPublicAccessLevel.Localizable.swift
Closes #68
It's useful to see the source localisation, especially now that it's no longer included in the generated code after #67. This change replaces the `Resource.defaultValue` property with a new `sourceLocalization` property and uses it for the `///` doc comment for each generated accessor.
> Include the source localisation value in the headerdoc comments

- README.md
- Sources/StringGenerator/StringGenerator.swift
- Sources/StringGenerator/SwiftSyntax/TokenSyntax+Types.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.FormatSpecifiers.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Localizable.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Multiline.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Positional.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Simple.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Substitution.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Variations.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerateWithPackageAccessLevel.Localizable.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerateWithPublicAccessLevel.Localizable.swift
In #50, we extended support to iOS 15+ by using `String.init(localized:defaultValue:table:bundle:locale:)`, but it turned out that there was no advantage to using this initialiser over using the original `String.init(format:locale:arguments:)` combined with `Bundle.localizedString(forKey:value:table:)`.
I thought that there was originally because I thought that the newer init allowed you to override the language with the `locale` argument, but it turned out that the `locale` is only used for formatting arguments (i.e decimals) and nothing else.
As a result, I have switched the generated code to use `String.init(format:locale:arguments:)`, which means that it will work across all OS versions now 🚀 
The only version constrained code is the use of `LocalizedStringResource`
> Bring support to all OS versions

- Sources/StringGenerator/StringGenerator.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.FormatSpecifiers.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Localizable.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Multiline.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Positional.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Simple.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Substitution.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Variations.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerateWithPackageAccessLevel.Localizable.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerateWithPublicAccessLevel.Localizable.swift
In 0.2.0, we moved away from generating `LocalizedStringResource` directly by instead generating a `String.{TableName}` struct. 
This struct was then available for use in a generated `String.init({tableName}:)` initialiser, as well as being used as the backbone of the generated `LocalizedStringResource` accessors. 
Up until now, the internals of the generated type have remained private. This was the case because I didn't anticipate a scenario where you would need to know the key/table/bundle since the initalizers are there for you. However since I learned that the pre-ios 16 apis for resolving strings do not let you change the language, this changes a bit...
In this PR, I've updated the generated code so that the internal properties of the generated type are all `internal`. This would in …
> Expose properties from generated structs for custom use

- Sources/StringGenerator/Extensions/SourceFileSyntax.swift
- Sources/StringGenerator/Extensions/SyntaxCollection.swift
- Sources/StringGenerator/Models/SourceFile_StringExtension_StringsTableStruct_ResourceAccessor.swift
- Sources/StringGenerator/Snippets/SourceFileSnippet.swift
- Sources/StringGenerator/Snippets/String/StringsTable/Argument/StringStringsTableArgumentEnumSnippet.swift
- Sources/StringGenerator/Snippets/String/StringsTable/BundleDescription/StringStringsTableBundleDescriptionCurrentComputedPropertySnippet.swift
- Sources/StringGenerator/Snippets/String/StringsTable/BundleDescription/StringStringsTableBundleDescriptionEnumSnippet.swift
- Sources/StringGenerator/Snippets/String/StringsTable/StringStringsTableDefaultValueComputedPropertySnippet.swift
- Sources/StringGenerator/Snippets/String/StringsTable/StringStringsTableResourceFunctionSnippet.swift
- Sources/StringGenerator/Snippets/String/StringsTable/StringStringsTableResourceVariableSnippet.swift
- Sources/StringGenerator/Snippets/String/StringsTable/StringStringsTableStructSnippet.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.FormatSpecifiers.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Localizable.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Multiline.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Positional.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Simple.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Substitution.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Variations.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerateWithPackageAccessLevel.Localizable.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerateWithPublicAccessLevel.Localizable.swift
The original generated code was split across many extensions. While nice, it was a bit hard to maintain. It makes more sense to just bring things into the main declarations.
> Refactor generated code to use less extensions 

- Sources/StringGenerator/Snippets/LocalizedStringResource/LocalizedStringResourceInitializerSnippet.swift
- Sources/StringGenerator/Snippets/SourceFileSnippet.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.FormatSpecifiers.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Localizable.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Multiline.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Positional.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Simple.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Substitution.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Variations.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerateWithPackageAccessLevel.Localizable.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerateWithPublicAccessLevel.Localizable.swift
`LocalizedStringResource.init(localizable:)` use to be `private`, but since we will add a similar initialiser for `Text` as part of #60, it maybe makes sense to expose this a bit more. 
Also because I plan to deprecate the duplicate accessors on `LocalizedStringResource`
> Change declaration and make `LocalizedStringResource.init(localizable:)` internal

- Package.swift
- README.md
- Sources/Documentation/XCStringsToolPlugin.docc/Using the generated source code.md
- Sources/StringGenerator/Extensions/IfExprSyntax.swift
- Sources/StringGenerator/Extensions/TokenSyntax+Types.swift
- Sources/StringGenerator/Models/SourceFile_StringExtension_StringsTableStruct.swift
- Sources/StringGenerator/Snippets/IfCanImportSnippet.swift
- Sources/StringGenerator/Snippets/LocalizedStringResource/LocalizedStringResourceInitializerSnippet.swift
- Sources/StringGenerator/Snippets/SourceFileSnippet.swift
- Sources/StringGenerator/Snippets/String/StringsTable/StringStringsTableStructSnippet.swift
- Sources/StringGenerator/Snippets/StringInterpolation/AppendFormatSpecifiableInterpolationsSnippet.swift
- Sources/StringGenerator/Snippets/StringInterpolation/ExpressibleByStringInterplationInitializerClosureSnippet.swift
- Sources/StringGenerator/Snippets/StringsTableConversionStaticMethodSnippet.swift
- Sources/StringGenerator/Snippets/SwiftUI/LocalizedStringKeyInitializerSnippet.swift
- Sources/StringGenerator/Snippets/SwiftUI/LocalizedStringKeyOverrideKeySnippet.swift
- Sources/StringGenerator/Snippets/SwiftUI/TextInitializerSnippet.swift
- Sources/Version/Version.swift
- Sources/xcstrings-tool/XCStringsTool.swift
- Tests/PluginTests/PluginTests.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.FormatSpecifiers.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Localizable.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Multiline.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Positional.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Simple.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Substitution.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Variations.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerateWithPackageAccessLevel.Localizable.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerateWithPublicAccessLevel.Localizable.swift
Closes #60 
While `LocalizedStringResource` might be the future, it's still not in a place today where it can be used all of the time. Much of SwiftUI still does not support this type and it's also not compatible with older OS versions.
Since we've already put the effort in to support older OSes in Foundation (#70, #50), it makes sense to do the same for SwiftUI.
This Pull Request brings some creative little extensions on top of `Text` and `LocalizedStringKey` that let you use the generated `String.Localizable` type across the entire API surface of SwiftUI on any OS version 🎉 
It does so with the following extensions:
```swift
extension Text {
/// Creates a text view that displays a localized string defined in the ‘Localizable‘ strings table.
internal init(localizable: String.Localizable) …
```
> Add backwards compatible initialisers for `Text` and `LocalizedStringsKey`

- Sources/StringGenerator/Snippets/String/StringsTable/Argument/StringStringsTableArgumentValueComputedProperty.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.FormatSpecifiers.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Localizable.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Multiline.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Positional.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Simple.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Substitution.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Variations.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerateWithPackageAccessLevel.Localizable.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerateWithPublicAccessLevel.Localizable.swift
The computed `value` property on the `Argument` enum was defined as `CVarArg`, which will result in a build failure in future versions of Swift.
We should include the `any` keyword.
> Use Existential `any`

- Sources/StringGenerator/Extensions/AttributeSyntax+Availability.swift
- Sources/StringGenerator/Models/SourceFile_LocalizedStringResourceExtension_StringsTableStruct_ResourceAccessor.swift
- Sources/StringGenerator/Snippets/LocalizedStringResource/LocalizedStringResourceStringsTableComputedPropertySnippet.swift
- Sources/StringGenerator/Snippets/LocalizedStringResource/StringsTable/LocalizedStringResourceStringsTableResourceFunctionSnippet.swift
- Sources/StringGenerator/Snippets/LocalizedStringResource/StringsTable/LocalizedStringResourceStringsTableResourceVariableSnippet.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.FormatSpecifiers.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Localizable.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Multiline.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Positional.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Simple.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Substitution.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Variations.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerateWithPackageAccessLevel.Localizable.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerateWithPublicAccessLevel.Localizable.swift
Closes #81 
In #82, we've introduced the static `LocalizedStringResource.localizable(_:)` method which allows you to use `String.Localizable` in order to create a `LocalizedStringResource` instance with the similar sugar that `LocalizedStringResource.String...` and `LocalizedStringResource.localizable` provided:
```diff
- Text(.localizable.foo)
+ Text(.localizable(.foo))
```
It's not so obvious what the difference is with type inference, so to explain some more:
```diff
- Text(LocalizedStringResource.localizable.foo)
+ Text(LocalizedStringResource.localizable(String.Localizable.foo))
```
This means that it's no longer worth the effort to generate `LocalizedStringResource.String` and as a result, we're going to remove it.
Before doing that though, I am going to mark it as soft-deprecated. …
> soft-deprecate old generated LocalizedStringResource extensions

- .github/scripts/compile-snapshots.sh
- Sources/StringGenerator/Extensions/String+BacktickIfNeeded.swift
- Sources/StringGenerator/Models/SourceFile_LocalizedStringResourceExtension_StringsTableStruct_ResourceAccessor.swift
- Sources/StringGenerator/Models/SourceFile_StringExtension_StringsTableStruct_ResourceAccessor.swift
- Sources/StringGenerator/Snippets/LocalizedStringResource/StringsTable/LocalizedStringResourceStringsTableResourceFunctionSnippet.swift
- Sources/StringGenerator/Snippets/LocalizedStringResource/StringsTable/LocalizedStringResourceStringsTableResourceVariableSnippet.swift
- Sources/StringGenerator/Snippets/String/StringsTable/StringStringsTableResourceFunctionSnippet.swift
- Sources/StringGenerator/Snippets/String/StringsTable/StringStringsTableResourceVariableSnippet.swift
- Tests/XCStringsToolTests/__Fixtures__/Localizable.xcstrings
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Localizable.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerateWithPackageAccessLevel.Localizable.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerateWithPublicAccessLevel.Localizable.swift
Closes #38 
For example, a key called `cotninue` would generate incorrectly and fail to compile. This change detects invalid identifiers and adds the appropriate backticks.
> Backtick variable/method names that conflict with Swift keywords

- Package.swift
If you use the xcstrings-tool repo (this one) directly so that you compile the CLI from source, it had previously been restricted to iOS/tvOS 16 and watchOS 9 despite the plugin generating code that was compatible with earlier OS versions.
It turns out that because the CLI, and even the build tool plugin are executed on the host build machine, we didn't actually need to specify deployment targets for other platforms, and by doing so, it was needlessly restricting us.
This PR removes those definitions so that if you prefer to use the plugin from source, you can. As long as you use macOS 13 or later.
> Remove deployment target specifications for non-macOS platforms

- Sources/StringGenerator/Snippets/LocalizedStringResource/LocalizedStringResourceStringsTableComputedPropertySnippet.swift
- Sources/StringGenerator/Snippets/LocalizedStringResource/StringsTable/LocalizedStringResourceStringsTableResourceFunctionSnippet.swift
- Sources/StringGenerator/Snippets/LocalizedStringResource/StringsTable/LocalizedStringResourceStringsTableResourceVariableSnippet.swift
- Tests/PluginTests/PluginTests.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.FormatSpecifiers.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Localizable.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Multiline.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Positional.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Simple.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Substitution.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Variations.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerateWithLegacyFilesCombined.Legacy.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerateWithLegacyStrings.Legacy.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerateWithLegacyStringsdict.Legacy.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerateWithPackageAccessLevel.Localizable.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerateWithPublicAccessLevel.Localizable.swift
In 0.4.0, we introduced `LocalizedStringResource.localized(_:)` to match the same method added to `LocalizedStringKey` and as a result, we deprecated the original generated code on the `LocalizedStringResource` type.
In 0.4.0 however, a warning was not omitted. In 0.5.0, I am now omitting a warning because this code will be removed from an upcoming release:
Please see the following from the 0.4.0 release notes:
> It is now preferred to use the `LocalizedStringKey.localizable(_:)` or `LocalizedStringResource.localizable(_:)` static methods instead of the `LocalizedStringResource.localizable` static property. The static property has been marked as deprecated. A warning will be emitted starting in 0.5.0 and the code will be completely removed in 1.0.0. See below for migrating your code:
> 
> …
> Add deprecation warnings to generated `LocalizedStringResource` API

- .github/workflows/benchmark.yml
- Sources/StringGenerator/Extensions/Array+Position.swift
- Sources/StringGenerator/Extensions/StructDeclSyntax.swift
- Sources/StringGenerator/Extensions/SyntaxProtocol.swift
- Sources/StringGenerator/Snippets/LocalizedStringResource/StringsTable/LocalizedStringResourceStringsTableStructSnippet.swift
- Sources/StringGenerator/Snippets/String/StringsTable/StringStringsTableStructSnippet.swift
I profiled the project recently and realised that we were iterating over the accessors, then mapping all of them after just to add two lines of spacing.
We can save a good chunk of time if we don't map and we don't iterate through the whole array again and instead if we just add the spacing in the first loop.
> Improve performance when generating source code for large Strings Catalogs

- .github/workflows/benchmark.yml
- .github/workflows/tests.yml
- Package.resolved
- Package.swift
- Sources/StringGenerator/Extensions/String+BacktickIfNeeded.swift
- Sources/StringGenerator/Snippets/IfCanImportSnippet.swift
- Sources/StringGenerator/StringGenerator.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.FormatSpecifiers.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Localizable.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Multiline.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Positional.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Simple.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Substitution.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Variations.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerateWithLegacyFilesCombined.Legacy.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerateWithLegacyStrings.Legacy.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerateWithLegacyStringsdict.Legacy.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerateWithPackageAccessLevel.Localizable.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerateWithPublicAccessLevel.Localizable.swift
- Closes https://github.com/liamnichols/xcstrings-tool/issues/97
Whitespace between `@available` and the opening `(` causes a compile failure in Swift 6. It was found in the generated code due to how Swift Syntax 5XX.X.X would format the output.
This Pull Request does the following:
- Patches the generated code with a simple regex find and replace
- Updates the Package.swift to support Swift Syntax 600.0.0 once it is released
- Adds CI checks to run against each major Swift Syntax version
- Removes the regex workaround when using Swift Syntax 600.0.0 since the formatter in this version fixes the original whitespace issue
- Fix some deprecation warnings and removes other workarounds when using Swift Syntax 600.0.0
> Support Swift 6 language mode and Swift Syntax 600.0.0

- .github/scripts/compile-snapshots.sh
- .github/workflows/tests.yml
- Sources/StringGenerator/Snippets/LocalizedStringResource/StringsTable/LocalizedStringResourceStringsTableStructSnippet.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.FormatSpecifiers.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Localizable.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Multiline.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Positional.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Simple.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Substitution.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Variations.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerateWithLegacyFilesCombined.Legacy.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerateWithLegacyStrings.Legacy.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerateWithLegacyStringsdict.Legacy.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerateWithPackageAccessLevel.Localizable.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerateWithPublicAccessLevel.Localizable.swift
While testing in preparation for 0.5.1, I realised that I am missing tests to ensure that the generated source actually compiles in Swift 6 language mode.
When adding them, I found that `LocalizableStringResource.Localizable` fails to compile when `public` because it's not annotated as `Sendable`. Therefore I also added this annotation.
> Compile snapshots using Swift 6 Language Mode

- Sources/Documentation/XCStringsToolPlugin.docc/Documentation.md
- Sources/Documentation/XCStringsToolPlugin.docc/Using the Command Line Interface.md
- Part of #32 
this change adds documentation for using the cli directly in advanced use cases (or when SPM plugins are bugged)
> Document using xcstrings-tool cli directly

- .github/workflows/tests.yml
- Package.resolved
- Package.swift
- https://www.swift.org/blog/swiftlang-github/
swift-syntax and swift-docc-plugin have moved to the swiftlang org on GitHub, while the existing links work, it can start to cause warnings to popup when mixing and matching urls. 
This change updates our dependency definitions to use the new org which is what will happen with all packages eventually.
I also drop the .git suffix from the urls since it is redundant. 
As part of this change, the pinned version of swift-snapshot-testing has been updated from 1.16.1 to 1.17.2.
> Pin dependencies to swiftlang GitHub organisation (was apple) and remove .git suffix

- .github/workflows/tests.yml
- Package.resolved
- Sources/xcstrings-tool/Utilities/AccessLevel+Resolution.swift
> Fix "'retroactive' attribute does not apply here" error when using Xcode 16 RC 

- Sources/StringGenerator/Snippets/SourceFileSnippet.swift
- Tests/PluginTests/PluginTests.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.FormatSpecifiers.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Localizable.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Multiline.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Positional.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Simple.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Substitution.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Variations.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerateWithLegacyFilesCombined.Legacy.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerateWithLegacyStrings.Legacy.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerateWithLegacyStringsdict.Legacy.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerateWithPackageAccessLevel.Localizable.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerateWithPublicAccessLevel.Localizable.swift
> Implements static string extension. 

- Sources/SwiftIdentifier/SwiftIdentifier+Extra.swift
- Tests/XCStringsToolTests/SwiftIdentifierTests.swift
If a Strings Catalog contained an uppercase acronym at the start, the variable  name generated would incorrectly only lowercase the first character.
For example:
URLStrings.xcstrings would generate a struct called `URLStrings` as expected, but the variable/label would be `uRLStrings` which is not expected.
In this PR, I update the logic so that we lowercase the n-1 initial characters if more than 1 character is uppercased at the start of the string.
This means that the example above will generate a variable named `urlStrings`
> Fix variable name from string catalog with an acronym in the name

- Sources/Documentation/XCStringsToolPlugin.docc/Integrating XCStrings Tool into a Swift Package Target.md
- Sources/StringGenerator/Models/SourceFile_StringExtension_StringsTableStruct.swift
- Sources/xcstrings-tool/Utilities/InputParser.swift
- Tests/PluginTests/Resources/fr.lproj/Legacy.strings
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.FormatSpecifiers.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Localizable.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Multiline.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Positional.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Simple.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Substitution.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Variations.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerateWithLegacyFilesCombined.Legacy.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerateWithLegacyStrings.Legacy.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerateWithLegacyStringsdict.Legacy.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerateWithPackageAccessLevel.Localizable.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerateWithPublicAccessLevel.Localizable.swift
Fixed a bunch of typos, keeping the British-English as the source of truth (based on the presence of the word `customise`)
> Enhance the documentation quality

- .github/workflows/build.yml
- .github/workflows/tests.yml
- https://github.com/actions/runner-images/issues/10703
This Pull Request updates the workflow configurations to use macOS 15 and Xcode 16.1 as the primary OS for checks.
In addition, some minor adjustments are made reflect changes in runner images as referenced in the ticket linked above.
> Update CI workflows to check Xcode 16.1 and macOS 15

- Sources/StringGenerator/Extensions/AttributeSyntax+Availability.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.FormatSpecifiers.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Localizable.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Multiline.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Positional.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Simple.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Substitution.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerate.Variations.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerateWithLegacyFilesCombined.Legacy.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerateWithLegacyStrings.Legacy.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerateWithLegacyStringsdict.Legacy.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerateWithPackageAccessLevel.Localizable.swift
- Tests/XCStringsToolTests/__Snapshots__/GenerateTests/testGenerateWithPublicAccessLevel.Localizable.swift
Availability was macOS 10.5 instead of the needed macOS 10.15
> Fix: macOS Support

- .github/workflows/tests.yml
There is a new prerelease out so we should be running tests against that instead.
> Update SwiftSyntax 6.2 tests to use 602.0.0-prerelease-2025-05-29
